FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/cloudify-operator ./cmd/cloudify-operator

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/cloudify-operator /cloudify-operator
USER nonroot:nonroot
ENTRYPOINT ["/cloudify-operator"]
